spring:
  application:
    name: coldMailSender
  mail:
    host: smtp.gmail.com
    port: 587
    username: yourfull@gmail.com
    password: toja piid gale lfbh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cold-mail:
  enabled: ${COLD_MAIL_ENABLED:true}
  template: coldmail.xml
  attachment-path: Narayana_Resume.pdf
  delay-millis: 4000
  recipients: ${RECIPIENTS:"gokulrao27@gmail.com","igokulrao27@gmail.com"}
